---
layout: cv
title: Tyler Bartle's Resume
---
# Tyler Bartle
Detail-oriented Computer Science student (3.99 GPA) at Brigham Young University—Idaho with 3+ years of coding experience, 4+ years of general work  experience, and a strong foundation in problem-solving, teamwork, and efficiency. Passionate about software development, with experience in multiple programming languages and a history of contributing to collaborative projects.

<div id="webaddress">
<a href="tman.bartleboy1@gmail.com">tman.bartleboy1@gmail.com</a>
| <a href="https://linktr.ee/tman7077">All my links!</a>
</div>

## Skills & Projects

Throughout my time as a computer science enthusiast, I have worked on quite a few projects. Many of them are uploaded on [my GitHub](https://github.com/tman7077) account! Most of my work has been in object-oriented and functional contexts, and I’ve worked in many languages: Python, C# and .NET 7-9, Elixir & Erlang, HTML & CSS, JavaScript, and SQL (MySQL). I’m also currently working on [a simple murder mystery application](https://github.com/tman7077/spaceteam-murder-mystery) in C# and WPF (*soon™*).

## Experience & Accomplishments

**Brigham Young University—Idaho** *(Current)*

- 3.99 GPA
- Senior, studying Computer Science

**Doherty High School** `May 2021`

- 4.23 GPA
- Two academic letters
- 96th percentile, rank 13/450+ in class

## Experience & Accomplishments

**Drop-in Lab Coordinator** `Apr 2025 - Current`

*Brigham Young University—Idaho* | *Rexburg, ID*

- Organized and managed operations in a computer science tutoring lab.
- Tutored one-on-one for more than 15 computer science courses offered by the university.

**Level 5 Associate** `Nov 2020 - Jan 2025`

*In-N-Out Burger* | *Colorado Springs, CO*  

- Provided high-quality customer service in a fast-paced environment, processing an average of 200+ orders per shift. 
- Trained and mentored new hires to improve team efficiency. 
- Maintained accuracy and speed in a high-volume setting, ensuring quality and customer satisfaction. 

---

- Teaching assistant for cybersecurity, cryptography, Linux, and discrete math 
- 1-on-1 math tutor from basic algebra to calculus, in general and specific fields 
- Missionary for the Church of Jesus Christ of Latter-day Saints 
- Eagle Scout in the Boy Scouts of America

<!-- ### Footer

Last updated: May 2013 -->